// Array of common usernames for simulation
const usernames = [
  "alex_23",
  "emma.smith",
  "jayden_98",
  "sophia.j",
  "ethan_wilson",
  "olivia.brown",
  "noah_22",
  "ava.jones",
  "liam_miller",
  "mia.davis",
  "jackson_44",
  "isabella.m",
  "aiden_33",
  "charlotte.p",
  "lucas_white",
  "amelia.g",
  "mason_55",
  "harper.t",
  "elijah_66",
  "evelyn.r",
  "logan_77",
  "abigail.w",
  "carter_88",
  "emily.b",
  "benjamin_99",
  "elizabeth.s",
  "michael_00",
  "sofia.l",
  "jacob_11",
  "madison.k",
  "fashion_lover22",
  "travel_addict",
  "fitness_guru",
  "food_enthusiast",
  "photo_pro",
  "music_fan",
  "art_creator",
  "nature_explorer",
  "tech_geek",
  "book_worm",
  "movie_buff",
  "sports_fanatic",
  "beauty_expert",
  "pet_lover",
];

// Array of common comments for simulation
const comments = [
  "🔥🔥🔥",
  "You look amazing!",
  "Hey from California!",
  "Love your content!",
  "Hello from Paris!",
  "Keep it up! 👏",
  "First time catching you live!",
  "Greetings from NYC",
  "You're so inspiring",
  "Can you do a tutorial on this?",
  "Love your energy",
  "This is awesome",
  "Hi from Australia! 🇦🇺",
  "What camera do you use?",
  "Your vibe is everything ✨",
  "Goals! 🙌",
  "I've been following you forever!",
  "This made my day",
  "So talented!",
  "Can't believe I caught you live",
  "Love the setup",
  "You're the best!",
  "This is exactly what I needed today",
  "Sending love from London ❤️",
  "I'm taking notes 📝",
  "Obsessed with this!",
  "Wow! 😍",
  "This is so cool",
  "You always have the best content",
  "I'm learning so much",
  "Can we collab sometime?",
  "Your style is everything",
  "This is why you're my favorite",
  "Needed this today",
  "Absolutely loving this",
  "You make it look so easy",
  "My favorite creator!",
  "This is gold",
  "Never miss your lives",
  "Such good vibes",
];

// Generate a random username
export const generateFakeUsername = (): string => {
  return usernames[Math.floor(Math.random() * usernames.length)];
};

// Generate a random comment
export const generateFakeComment = (): string => {
  return comments[Math.floor(Math.random() * comments.length)];
};
